
package com.interfactura.firmalocal.cifras.ws;

import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceFeature;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
//@WebServiceClient(name = "WebService1", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://santandes.interfactura.com/TimbreServiciosSantander/TimbreServicios.asmx?wsdl")
//@WebServiceClient(name = "WebService1", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://santanqa.interfactura.com/TimbreServiciosSantander/TimbreServicios.asmx?wsdl")
public class WebServiceCifras
    extends Service
{
	
	
    private final static URL WEBSERVICE1_WSDL_LOCATION = null;
    private final static Logger logger = Logger.getLogger(com.interfactura.firmalocal.cifras.ws.WebServiceCifras .class.getName());
/*
    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tempuri.WebService1 .class.getResource(".");
            //url = new URL(baseUrl, "https://santandes.interfactura.com/TimbreServiciosSantander/TimbreServicios.asmx?wsdl");
            url = new URL(baseUrl, "https://santanqa.interfactura.com/TimbreServiciosSantander/TimbreServicios.asmx?wsdl");
            
        } catch (MalformedURLException e) {
            //logger.warning("Failed to create URL for the wsdl Location: 'https://santandes.interfactura.com/TimbreServiciosSantander/TimbreServicios.asmx?wsdl', retrying as a local file");
        	logger.warning("Failed to create URL for the wsdl Location: 'https://santanqa.interfactura.com/TimbreServiciosSantander/TimbreServicios.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICE1_WSDL_LOCATION = url;
    }
*/

    public WebServiceCifras(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceCifras() {
        //super(WEBSERVICE1_WSDL_LOCATION, new QName("http://tempuri.org/", "WebService1"));
    	super(WEBSERVICE1_WSDL_LOCATION, new QName("http://tempuri.org/", "Service1"));
    }

    /**
     * 
     * @return
     *     returns WebService1Soap
     */
    @WebEndpoint(name = "WebServiceCifrasSoap")
    public WebServiceCifrasSoap getWebService1Soap() {
        //return super.getPort(new QName("http://tempuri.org/", "WebService1Soap"), WebService1Soap.class);
    	return super.getPort(new QName("http://tempuri.org/", "Service1Soap"), WebServiceCifrasSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService1Soap
     */
    @WebEndpoint(name = "WebServiceCifrasSoap")
    public WebServiceCifrasSoap getWebServiceCifrasSoap(WebServiceFeature... features) {
        //return super.getPort(new QName("http://tempuri.org/", "WebService1Soap"), WebService1Soap.class, features);
    	
    	return super.getPort(new QName("http://tempuri.org/", "Service1Soap"), WebServiceCifrasSoap.class, features);
    }

}
