
package com.interfactura.firmalocal.cifras.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebServiceCifrasSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceCifrasSoap {


    /**
     * 
     * @param soloTimbrado
     * @param fechaTimbrado
     * @param uuid
     * @return
     *     returns java.lang.String
     */
	/*
    @WebMethod(operationName = "ConsultaTimbre", action = "http://tempuri.org/ConsultaTimbre")
    @WebResult(name = "ConsultaTimbreResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaTimbre", targetNamespace = "http://tempuri.org/", className = "com.interfactura.firmalocal.xml.timbrado.ConsultaTimbre")
    @ResponseWrapper(localName = "ConsultaTimbreResponse", targetNamespace = "http://tempuri.org/", className = "com.interfactura.firmalocal.xml.timbrado.ConsultaTimbreResponse")
    public String consultaTimbre(
        @WebParam(name = "UUID", targetNamespace = "http://tempuri.org/")
        String uuid,
        @WebParam(name = "FechaTimbrado", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fechaTimbrado,
        @WebParam(name = "SoloTimbrado", targetNamespace = "http://tempuri.org/")
        boolean soloTimbrado);
*/
    /**
     * 
     * @param cfDv3
     * @param solotimbre
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GeneraCifrasControl", action = "http://tempuri.org/GeneraCifrasControl")
    @WebResult(name = "GeneraCifrasControlResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GeneraCifrasControl", targetNamespace = "http://tempuri.org/", className = "com.interfactura.firmalocal.cifras.ws.GeneraCifrasControl")
    @ResponseWrapper(localName = "GeneraCifrasControlResponse", targetNamespace = "http://tempuri.org/", className = "com.interfactura.firmalocal.cifras.ws.GeneraCifrasControlResponse")
    public String generaCifrasControl(
        @WebParam(name = "fecha", targetNamespace = "http://tempuri.org/")
        String fecha,        
        @WebParam(name = "tipoFormato", targetNamespace = "http://tempuri.org/")
        int tipoFormato,
        @WebParam(name = "nombreInterfaz", targetNamespace = "http://tempuri.org/")
        String nombreInterfaz,
        @WebParam(name = "esReproceso", targetNamespace = "http://tempuri.org/")
        int esReproceso);

    /**
     * 
     * @param cancelaXML
     * @return
     *     returns java.lang.String
     */
    /*
    @WebMethod(operationName = "CancelaTimbre", action = "http://tempuri.org/CancelaTimbre")
    @WebResult(name = "CancelaTimbreResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelaTimbre", targetNamespace = "http://tempuri.org/", className = "com.interfactura.firmalocal.xml.timbrado.CancelaTimbre")
    @ResponseWrapper(localName = "CancelaTimbreResponse", targetNamespace = "http://tempuri.org/", className = "com.interfactura.firmalocal.xml.timbrado.CancelaTimbreResponse")
    public String cancelaTimbre(
        @WebParam(name = "CancelaXML", targetNamespace = "http://tempuri.org/")
        String cancelaXML);
*/
}
